### ISSUE TITLE
Example fib.c and FFI do not compile on FreeBSD

### ISSUE THREAD

**Issue by ALPHA-60** [austral/austral#277]
Hi! I just wanted to say that, as someone writing Ada from time to time, I really like some of the design decision that you made in Austral.

I couldn't compile the emitted fib.c from README file on FreeBSD:

```
/usr/local/bin/ld: /tmp//cce7YUxI.o: in function `au_abort_internal':
fib.c:(.text+0x25): undefined reference to `stderr'
/usr/local/bin/ld: fib.c:(.text+0x42): undefined reference to `stderr'
/usr/local/bin/ld: /tmp//cce7YUxI.o: in function `au_abort':
fib.c:(.text+0x78): undefined reference to `stderr'
/usr/local/bin/ld: fib.c:(.text+0x91): undefined reference to `stderr'
collect2: error: ld returned 1 exit status
```

I naively included  `stdio.h` in `lib/prelude.c` and fixed the declarations to correspond to `stdio.h` prototypes, which made the fib.c compile:

```patch
diff --git a/lib/prelude.c b/lib/prelude.c
index 2881599d..3b46c029 100644
--- a/lib/prelude.c
+++ b/lib/prelude.c
@@ -1,3 +1,4 @@
+#include <stdio.h>
 #include <stdint.h>
 #include <stddef.h>
 #include <stdarg.h>
@@ -43,10 +44,10 @@ au_array_t au_make_array_from_string(const char* data, size_t size) {
 }
 
 au_unit_t au_abort_internal(const char* message) {
-  extern int fprintf(void* stream, const char* format, ...);
-  extern int fflush(void* stream);
+  extern int fprintf(FILE* stream, const char* format, ...);
+  extern int fflush(FILE* stream);
   extern void _Exit(int status);
-  extern void* stderr;
+  extern FILE* stderr;
 
   fprintf(stderr, "%s\n", message);
   fflush(stderr);
@@ -56,10 +57,10 @@ au_unit_t au_abort_internal(const char* message) {
 }
 
 au_unit_t au_abort(au_array_t message) {
-  extern int fprintf(void* stream, const char* format, ...);
-  extern int fflush(void* stream);
+  extern int fprintf(FILE* stream, const char* format, ...);
+  extern int fflush(FILE* stream);
   extern void _Exit(int status);
-  extern void* stderr;
+  extern FILE* stderr;
 
   fprintf(stderr, "%s\n", (char*) message.data);
   fflush(stderr);
```

Unfortunately, this creates issues when compiling `examples/ffi/FFI`, because generated code for "puts" and "putchar" conflicts with stdio definitions; built-in putchar is a macro which makes emitted `code.c` syntactically invalid, and `puts` has a different signature:

```
code.c: In function 'decl_97':
code.c:2452:23: error: expected identifier or '(' before '!' token
 2452 |     extern au_int32_t putchar(au_int32_t character);
      |                       ^~~~~~~
code.c: In function 'decl_98':
code.c:2460:23: error: conflicting types for 'puts'
 2460 |     extern au_int32_t puts(uint8_t* str);
      |                       ^~~~
In file included from code.c:2:
/usr/local/gcc-fsf-gnat/lib/gcc/x86_64-fsf-freebsd13.0/10.3.0/include-fixed/stdio.h:293:6: note: previous declaration of 'puts' was here
  293 | int  puts(const char *);
      |      ^~~~
```
 
 This happens with both clang and gcc.
 
I only took a glance at Austral source, so I don't have any suggestions on how to resolve this, but I'd be glad to test on FreeBSD if it helps (and if it's of any priority).

**Comment by eudoxia0** [comment]
This is a problem I've had in the past with MacOS. As you have explained, the solution is not straightforward.

- Including the header files conflicts with other declarations.
- Not including the header files leads to errors because some platforms have weird names for symbols.

The trivial solution is to not embed the prelude source code, but that places an added burden on the programmer to compile the prelude themselves when they call GCC and link it with the code (a build system could do this, but I don't have one yet). Having the generated code be standalone is useful.

I think I have a solution, but have no easy way to test it.

**Comment by eudoxia0** [comment]
@ALPHA-60 this is a bit of a hack, but could you test if https://github.com/austral/austral/pull/278 works?

**Comment by ALPHA-60** [comment]
Thanks, this approach works (it just needs a similar fix in `au_abort`), though it does feel brittle.

I took a quick look at what ECL and Cython do, since they also output C source, and maybe an approach similar to ECL's [SFFI](https://ecl.common-lisp.dev/static/manual/Foreign-Function-Interface.html#Two-kinds-of-FFI) or Cython's "[extern from](https://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html#referencing-c-header-files)" could be something to consider, at least while Austral primarily outputs C. I'm thinking of something on the lines of:

```
function Put_Char(character: Int32): Int32 is
    pragma Foreign_Import(
        External_Name  => "putchar"
        Include_File   => "stdio.h");
end;
```

which would generate the include directive and a wrapped C function call but no `extern` declarations which could conflict with ones included in the prelude.

Thanks again for the fix!

**Comment by yx-programming** [comment]
Would also like to note that this issue occurs in OpenBSD as well. However, I was able to solve any missing symbols/symbol collisions by removing the `extern` statements at fault and adding `#include <stdio.h>` to the beginning of the file. Is there any particular reason that these statements are there? The program appeared to work as expected for the Hello World example and the FFI example.

**Comment by eudoxia0** [comment]
@ALPHA-60 

> Thanks, this approach works (it just needs a similar fix in `au_abort`), though it does feel brittle.

I will update this, thanks.

> I took a quick look at what ECL and Cython do, since they also output C source, and maybe an approach similar to ECL's [SFFI](https://ecl.common-lisp.dev/static/manual/Foreign-Function-Interface.html#Two-kinds-of-FFI) or Cython's "[extern from](https://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html#referencing-c-header-files)" could be something to consider, at least while Austral primarily outputs C. I'm thinking of something on the lines of:
> 
> ```
> function Put_Char(character: Int32): Int32 is
>     pragma Foreign_Import(
>         External_Name  => "putchar"
>         Include_File   => "stdio.h");
> end;
> ```
> 
> which would generate the include directive and a wrapped C function call but no `extern` declarations which could conflict with ones included in the prelude.

This would work. However, I think it ties the FFI too much to C.

The C backend is not meant as a first-class language feature, but as an implementation detail mostly.

The FFI, as presently designed, works basically for any native backend. The linker resolves the symbols. If I were to add an LLVM backend, the current FFI would work for that backend also.

Ultimately the general solution is, when I have a build system written, I can have it compile the prelude separate, and link it transparently when calling the C compiler. This takes the burden from the user.

But in the meantime, I will merge the quick solution.

**Comment by eudoxia0** [comment]
@ALPHA-60 @yx-programming I've merged #278, and if either of you can confirm that it works on your operating system I'll close this as fixed.

**Comment by yx-programming** [comment]
On OpenBSD this approach doesn't work. I dug through the `stdio.h` system header, and it seems to fail because OpenBSD does not define `__stderrp`. Rather, it defines `stderr` as a macro pointing to `&__sF[2]`. Replacing the current solution in the `#if` with
```c
extern void *__sF;
return &__sF[2];
```
will compile without an error and run as expected for the FFI example. I checked this in the Array and GenericRecord examples as well and these both compiled. The compiler does warn about dereferencing a  void pointer, but this does not actually cause issues.

**Comment by eudoxia0** [comment]
@yx-programming does #279 work for you?

**Comment by yx-programming** [comment]
Yep, that works! Thanks for fixing that! Sorry to hijack this issue, but it seemed better than opening another issue for a problem with the same cause. I'm really excited about the language, and can't wait to try it out.

**Comment by eudoxia0** [comment]
@yx-programming No worries, thanks for taking the time to test!
