### ISSUE TITLE
Discrepancy in allocate function

### ISSUE THREAD

**Issue by jacereda** [austral/austral#309]
According to the spec:

> 
> allocate Function
> Declaration:
> 
> generic [T: Type]
> function allocate(size: Natural_64): Pointer[T];
> Description:
> 
> Allocates the given amount of memory in bytes.
> 

But the code seems to allocate space for size*sizeof(T) elements:

https://github.com/austral/austral/blob/cda5a2082ae13b99c1c9d919309a5cdbf4bc2662/lib/builtin/Memory.aum#L25

Is the spec wrong?

**Comment by eudoxia0** [comment]
Yep the spec is wrong, thanks for reporting!
