### ISSUE TITLE
working with foreign types

### ISSUE THREAD

**Issue by scolsen** [austral/austral#338]
Is there support in Austral yet for using external types defined in C and including C libraries? 

e.g. I'd like to do something like:

```
module IO.File is

  extern type FILE;

  function fopen(): FILE;

end module.
```

Where the resulting C would produce the name `FILE` as-is, and ideally there'd be some way to `include` a C header like `stdio` in the output.

**Comment by eudoxia0** [comment]
No explicit support for this---the way you'd do it is define an Austral type that you know is compatible with the C type. Of course this is hard to do in a cross-platform manner. But just getting the width right should be enough. For example, the `FILE` pointer type is just an opaque pointer.

**Comment by scolsen** [comment]
Got it, thanks!
