### ISSUE TITLE
Discord link dead?

### ISSUE THREAD

**Issue by elszben** [austral/austral#340]
Hi, I saw the language on hacker news. I believe your language and my language are very similar and there is a strong possibility of cooperation here or at least I think it is worth exploring the idea. I wanted to follow the link to your discord server to start a conversation but the invite seems to be dead and/or it expired. Could you please check it?

Thanks!

**Comment by timmyjose** [comment]
I just tried from the reddit post, and it's working. Here is an invite - https://discord.gg/kA95YUk2

**Comment by eudoxia0** [comment]
Sorry folks, the first link was time/user count limited. I believe the current README link should work.
