### ISSUE TITLE
Spritely and Object Capability Network

### ISSUE THREAD

**Issue by aschrijver** [austral/austral#341]
(Sorry, I am not using Discord, but Matrix for all FOSS projects I'm involved with. This issue is just a heads-up and you may close right away)

I read the [introduction](https://borretti.me/article/introducing-austral) and impressed by the approach taken. A language "that fits in your head". Esp. compared to Scala, where I once did a course, which imho is a language where academics went wild in adding language candy.

The native support for Object Capabilities is super interesting, and I came here to point to some very noteworthy developments taking place in this area. The [Spritely Institute](https://spritely.institute), founded by Christine Lemmer-Webber and Randy Farmer, are working on standardizing an [Object Capabilities Network](https://github.com/ocapn/ocapn). The institute was preceded by the [Spritely Project](https://spritelyproject.org/) started by Christine, a co-author of the W3C ActivityPub open standard (think Mastodon et al). There's a whitepaper giving an overview: [The Heart of Spritely: Distributed Objects and Capability Security](https://spritely.institute/static/papers/spritely-core.html). Various other projects are also involved with the OCapN efforts, like [Sandstorm](https://sandstorm.io/) who use [Cap'n Proto](https://capnproto.org/) protocol.

Might be interesting to weigh if Austral with its native support might hook into this research in some way or other :)

Spritely Institute can be found on the Fediverse at [@spritelyinst@octodon.social](https://octodon.social/@spritelyinst) and at #spritely Libera Chat IRC channel (bridged to a [Matrix chatroom](https://matrix.to/#/#spritely:libera.chat)).

**Comment by eudoxia0** [comment]
>I read the [introduction](https://borretti.me/article/introducing-austral) and impressed by the approach taken. A language "that fits in your head". Esp. compared to Scala, where I once did a course, which imho is a language where academics went wild in adding language candy.

Thanks!

>Might be interesting to weigh if Austral with its native support might hook into this research in some way or other :)

Thank you for the reference. I'm not sure where to file this for future reference. But this is really interesting, especially the Guile integration. I've followed them on Twitter so I can stay on top of this.

**Comment by aschrijver** [comment]
In follow-up - to keep this as comms channel for a bit, sorry @eudoxia0 - I received particular [feedback on Austral](https://elixirforum.com/t/elixir-and-object-capabilities/52311/9?u=aschrijver) on the Elixir Community Forum where I posted a link to your article. The info is a bit over my head to formulate a good response to.

**Comment by eudoxia0** [comment]
I can reply here:

>“no exceptions” is only technically true, as there are no user-observable exceptions and no mechanism for cleaning user-defined things up when something goes wrong. There’s still PLENTY of places that call abort and hard-exit from the OS process

This is justified here: https://austral-lang.org/spec/spec.html#rationale-errors

Basically, there's a difference between invariant violations and userspace errors.

Invariant violations are like arithmetic where the operands would overflow, or array out of bounds indexing. This is a bug: it crashes the program.

Userspace "errors" are things like "fopen: file not found" or a failing network connection. This should be handled with the errors-as-values approach. Does does this very reliably.

>the first place that users might reasonably expect to encounter capabilities is when they want to print to the terminal, but Austral works around that because it would be too verbose

Look, there's really no good solution here:

1. **Capability-secure terminal IO:** most people will open the tutorial, see that "Hello, world!" is like seven lines of code for the capability setup (and the more granular the capabilities, the longer the code gets), and close the tab right then and there. It is asking a lot of people to go "please ignore all this giant seeming boilerplate".
2. **No capability-secure terminal IO:** then people can complain that it's not Truly Secure.

I think I'll probably err on the side of making the API capability-secure. But it is asking a lot of the programmer who just wants to get something done.

>another place to encounter capabilities might be when directly manipulating memory (for instance, type-punning with memmove) but that’s also side-stepped with a specific “are you importing the Memory module?” check

This is a good point. A `MemoryAccess` capability (and possibly `MemoryRead` and `MemoryWrite` sub-capabilities) would be an interesting choice. But the problem then is anything that uses the FFI (which is anything) has to be passed a memory capability, alongside something else. It would be inconvenient.

But I'm open to suggestions about what the API should look like.

>borrowing is powerful, but also brings plenty of edge-cases. For instance, in the example “capability-based file API”, what happens if a Path value is created using the borrowed result of Get_Filesystem but the Path is still in-scope after Release_Filesystem has been called? Should a call to Read_File succeed, or crash? Can/should the compiler catch this? It may not even be an error :thinking: - for instance, I could imagine a capabilities API where best-practice was to derive smaller capabilities at the beginning of a program and then discard the root capability, similar to how setuid programs “drop root” as soon as it’s no longer needed.

The solution here (if I understood the question correctly) is basically that capabilities don't _necessarily_ have to be live throughout all of the code that uses them. This depends on the design of the specific API, but typically, you only need a capability at the "entrypoint" to the API, so to speak, to prove you can access it at all. Again, this depends on the specific design, there's many ways to implement specific APIs to use capabilities. I wish I had more examples on hand to demonstrate this, unfortunately I'll have to write more of the stdlib for this.

**Comment by aschrijver** [comment]
Thank you very much for the response. I will be sure to notify in the forum.

**Comment by eudoxia0** [comment]
@aschrijver do you want me to move this thread to https://github.com/austral/austral/discussions for possible future discussion?

**Comment by aschrijver** [comment]
Yes, please, thank you.
