### ISSUE TITLE
Austral generates invalid C code when a linear record references a free record

### ISSUE THREAD

**Issue by qbradley** [austral/austral#358]
The following test program generates C code, but the C fails to compile:

```
module body Test is
    record Bar: Free is
    end;

    record Foo: Linear is
        bar: Bar;
    end;

    function main(): ExitCode is
        return ExitSuccess();
    end;
end module body.
```

I try to compile the above program using:

austral compile Test.aum --entrypoint=Test:main --output=test

Expected result:

Compiles and runs

Actual result:

```
Error:
  Title: Generic Error
  Module:
    [unknown]
  Location:
    [no span available]
  Description:
    Error when running C compiler.
      Command: cc /tmp/austral_1b5b94.c -fwrapv -lm -o test
      Exit code: 1
      Standard output:

      Standard error:
    /tmp/austral_1b5b94.c:3478:17: error: unknown type name 'mono_12'
     3478 | typedef struct {mono_12 bar;} decl_205;
          |                 ^~~~~~~

  Code:
    [no span available]
```

Examining the generated C code, I see the following snippet:

```c
/*
  Record
*/
typedef struct {mono_12 bar;} decl_205;

/*
  Record monomorph: Bar[]
*/
typedef struct {} mono_12;
```

If I reorder these definitions and recompile the C code, it compiles and runs as expected.

**Comment by eudoxia0** [comment]
Thank you for reporting. I'll have to look at this tomorrow (it's 2am) here. But in the meantime I've opened a PR with a regression test for this: https://github.com/austral/austral/pull/360

**Comment by qbradley** [comment]
In the meanwhile I found a workaround.  In the actual situation where I ran into this bug originaly, I have a linear record X with field of type Buffer[Y] where Y is free record Z.  I created a new module and put the definition of Z in it, and then I created a method in the module that takes Buffer[Z] as a parameter.  This forces creation of Buffer[Z] related types during that module output, and since the modules are processed in order, they definitions exist before my record X and it all works.

I had another Buffer[Nat32] that also hit this bug, and by adding that as a parameter to the never called method in my extra module, that was resolved as well.

**Comment by nsanmartin** [comment]
It looks like `mono_12` corresponds to `Bar` and `decl_205` to `Foo`. If that true, while `mono_12` has a comment indicating that, `decl_205` hasn't. Wouldn't it be nice to have it commented as well in the generated c code?

**Comment by eudoxia0** [comment]
@qbradley I've been very busy this week, but this is getting fixed before Sunday.

**Comment by qbradley** [comment]
Thank you, I appreciate it!

**Comment by eudoxia0** [comment]
@nsanmartin yes I'd like to track some more metadata so I can print comments alongside the source code describing provenance, but that's a bit of work.

**Comment by eudoxia0** [comment]
@qbradley This turned out to be a lot simpler than I expected.
