### ISSUE TITLE
Experimenting with generic records, assertion failure in `TypeParser.ml`

### ISSUE THREAD

**Issue by timmyjose** [austral/austral#359]
Code:

```
module body LinearReferences is
  record Foo[R: Region] : Linear is
    x : Int32;
    y : Bool;
    r : R;
  end;

  generic [R : Region]
  function bar(r : &[Foo, R]) : Unit is
    return nil;
  end;

  function main() : ExitCode is
    return ExitSuccess();
  end;
end module body.
```

Behaviour: 

```
Fatal error: exception File "lib/TypeParser.ml", line 267, characters 2-8: Assertion failed
make: *** [LinearReferences] Error 2
```

Additional observations: 

  1. If I comment out the definition of `bar`, it compiles, but I suspect that's just a side-effect, and not a meaningful phenomenon by itself.
  2. If I replace the `Region` part in the definition of the record `Foo` with `Linear`, `Type`, or `Free`, the exhibited behaviour is the same.

**Comment by eudoxia0** [comment]
I will look at this in more depth tomorrow (it's very late here) but I think (looking at the line where the assertion is raised, which really should be a proper error message) it's an arity error: `Foo` is a generic type that takes one `Region` parameter, so valid type specifiers are of the form `Foo[R]`.

I think something like this should work:

```
module body LinearReferences is
  record Foo : Linear is
    x : Int32;
    y : Bool;
  end;

  generic [R : Region]
  function bar(r : &[Foo, R]) : Unit is
    return nil;
  end;
```

**Comment by timmyjose** [comment]
> I wrote some code to improve the error message: #362
> 
> When I run your code through this version of the compiler, it prints the following:
> 
> ```
> Error:
>   Title: Generic Error
>   Module:
>     LinearReferences
>   Location:
>     [no span available]
>   Description:
>     The type `Foo` expects `1` type arguments, but I only found `0` arguments.
>   Code:
>     [no span available]
> ```
> 
> The error is on line 9, in the type of `r`.
> 
> Is this helpful?

Hey @eudoxia0. I did an update, and I get the same error message now. I am not sure about the full implications of my code itself (I was experimenting), and if I change the signature of the function `bar` to:

```
  generic [R : Regsion]
  function bar(r : &[Foo[R], R]) : Unit
```

it compiles just fine. However, does this code even make sense - I cannot find any way to create a value of `Foo` inside `bar`? I don't know to be honest. 

However, I'm closing the issue now since I get a compile-time error message about the generic record `Foo` itself.
