### ISSUE TITLE
Multiple type parameters to typeclass

### ISSUE THREAD

**Issue by ishehadeh** [austral/austral#367]
Currently, typeclasses only accept a single type argument, is this an intentional limitation?

I ran up against it trying to write a `Mapping` typeclass:
```
typeclass Mapping(K: Type, V: Type) is
    method set(k: K, v: V): Unit;
    method get(k: K): Optional[V];
end;
```

**Comment by eudoxia0** [comment]
Yes it is intentional. It's more tractable. I'm open to arguments on how to do this while maintaining simplicity and tractability.

**Comment by ishehadeh** [comment]
Makes sense. I guess it forces type classes to be much smaller and more focused. My issue is that it makes pretty simple abstract types difficult or impossible, like the above example. I worry that would lead to more complexity down the road. It might cause people to use concrete types when they aren't appropriate, like in library interfaces; or encourage weird workarounds.

**Comment by eudoxia0** [comment]
I mean, you can have multi-parameter generic types, like a `Map[K,V]` type.

Associated types are probably a better solution than multiparameter type classes (which is why Rust and Swift use them).

**Comment by ishehadeh** [comment]
A `type`  is just a type declaration right? Can it have multiple implementations? 

The idea with a mapping type class would be allowing the user to easily swap out a btree for a hash map or similar data structure.

As far as I understand associated types wouldn't work in this case either, since the implementation would (usually) also be generic over K, V.

**Comment by eudoxia0** [comment]
>A type is just a type declaration right? Can it have multiple implementations?

How do you mean? Each type declaration in the interface matches a type definition in the module.

>As far as I understand associated types wouldn't work in this case either, since the implementation would (usually) also be generic over K, V.

Well the problem is: the rules for Haskell 98-style single parameter typeclasses are very clear. What should the rules be for multi-parameter type classes to make things both flexible and simple?

**Comment by ishehadeh** [comment]
Makes sense I'm not all that familiar with Haskell but looking at the multi parameter vs single parameter type classes it does seem like the multi parameter ones are way more complicated. 

Thanks, closing this now.
