### ISSUE TITLE
Destructuring a linear field with renaming confuses the linearity checker

### ISSUE THREAD

**Issue by qbradley** [austral/austral#373]
When a record contains a field that has a linear type, and you destructure it while renaming, the linearity checker complains that the original name is not consumed.

For example, the following program should compile but does not:

```
module body Test is
    record B : Linear is
        x : Int32;
    end;
    record A : Linear is
        b: B;
    end;

    function main(): ExitCode is
        let a: A := A(b => B(x => 5));
        let { b as b1: B } := a;
        let { x as x1: Int32 } := b1;
        return ExitSuccess();
    end;
end module body.
```

Instead of compiling, you get the following error:

```
Variable `b` not consumed at return statement.
```

If you remove the renaming as follows, it works:

```
        let { b: B } := a;
        let { x as x1: Int32 } := b;
```

And the following also works:

```
        let { b: B } := a;
        let b1: B := b;
        let { x as x1: Int32 } := b1;
```

**Comment by eudoxia0** [comment]
Added a test: #374

**Comment by eudoxia0** [comment]
Turns out this was a very short fix! :smile:
