### ISSUE TITLE
C compilation failure when using constant in constant record initialization

### ISSUE THREAD

**Issue by qbradley** [austral/austral#375]
I hope these bug reports are useful. I'm trying to write a hashtable in Austral and it is the bugs I run into.

I created a constant Record initialized with another constant, and I get a C compliation failure:

```
module body Test is

    record R: Free is
        x: Nat32;
    end;

    constant one: Nat32 := 1;
    constant r_one: R := R(x => one);

    function main(): ExitCode is
        return ExitSuccess();
    end;
end module body.
```

The error is:

```
--- BEGIN GCC STDERR ---
test-programs/output.c:3459:36: error: initializer element is not constant
 3459 | mono_12 Test____r_one = ((mono_12) { .x = Test____one });
      |                                    ^
test-programs/output.c:3459:36: note: (near initialization for ‘Test____r_one’)
test-programs/output.c:3459:25: error: initializer element is not constant
 3459 | mono_12 Test____r_one = ((mono_12) { .x = Test____one });
      |                         ^

--- END GCC STDERR ---
```

If I replace r_one definition with this it works:

```
    constant r_one: R := R(x => 1 : Nat32);
```

And the following also works in a function:

```
    let r_one: R := R(x => one);
```

**Comment by eudoxia0** [comment]
>I hope these bug reports are useful.

Yes they are! Thank you for trying it out and reporting frustrations.

**Comment by eudoxia0** [comment]
I think struct initializers for global variables might not be portable C. Which is a problem. Hm. It might be time to implement that LLVM backend, which is not that difficult in the first place, and which probably has better-defined behaviour for this case.

**Comment by eudoxia0** [comment]
Added a test here: #376

**Comment by qbradley** [comment]
If we want to stick with C backend, could it be solved by making constants "lazy" and emitting the code for them when they are reference in a function.  Since reference to the constant value worked in a "let", I imagine that might work.  Maybe C compilers are smart enough to intern const struct initializations, so might not result in code bloat but I'm just guessing that they do by analogy with constant string behavior.

**Comment by qbradley** [comment]
actually there is a simple workaround I can use now.

I can replace my r_one definition with

```
function rOne(): R is
    return R(x => one);
end;
```

and then use `rOne()` anywhere I was using `r_one`

**Comment by eudoxia0** [comment]
Yes, a function returning a constant defined in the body will work. Obviously not entirely ideal.

**Comment by eudoxia0** [comment]
Fixed this, somewhat less than acceptably, by codegen'ing constants as macros.
