### ISSUE TITLE
JSON Error Reporting

### ISSUE THREAD

**Issue by eudoxia0** [austral/austral#388]
Right now, the [end-to-end tests](https://github.com/austral/austral/tree/c07274d2ab1d37d1fccfca4fc0553b3d38c8f5a0/test-programs) rely on the compiler's human-readable error output (see for [example](https://github.com/austral/austral/blob/c07274d2ab1d37d1fccfca4fc0553b3d38c8f5a0/test-programs/suites/011-bugs/github-381b/austral-stderr.txt)). This isn't great: any aesthetic changes to the way errors are rendered to the user would require updating all of the tests.

It would be good to have a way to print errors as JSON values, so that they are not expected to change too much.

Tasks:

1. Depend on some or another JSON library.
2. Write a function to transform error objects into JSON.
3. Add an appropriate flag to the command line parser.
4. Wire everything together.

**Comment by Atli-A** [comment]
I think to tackle issue we need an example to follow. This is my idea of what it should look like as of now:

`"error"` is an object so that it can be null if there is no error.
```json
{
  "error": {
    "type": "<str>", // ex: Parse Error
    "module": "<str>", // ex: Standard.Buffer
    "location": {
      "filename": "<str>",
      "startp": {
        "line": "<num>",
        "column": "<num>"
      },
      "endp": {
        "line": "<int>",
        "column": "<num>"
      }
    },
    "description": "<str>",
    "code_block": "<str>"
  }
}
```
