### ISSUE TITLE
License the standard library as Apache 2.0

### ISSUE THREAD

**Issue by eudoxia0** [austral/austral#390]
Right now the only license notice is GPLv3 which I intended to apply only to the compiler, and not the builtins and standard library. And of course I have to clarify this.

So I'd like to explicitly license the stdlib as Apache 2.0, which is permissive, legally precise, and widely used.

@jacereda since you're the only other person who's [committed](https://github.com/austral/austral/commit/42f1de2288fa61bbdeee1d68d86f7455f0343cd9) to the standard library: do you approve of making this change?

**Comment by jacereda** [comment]
Sure, no problem.
