### ISSUE TITLE
Licensing the runtime as Apache 2.0

### ISSUE THREAD

**Issue by eudoxia0** [austral/austral#409]
As in #390: the only license in the repo is GPLv3, which naturally I only meant to apply to the compiler, so I should explicitly apply a permissive license to the runtime (which is included with every program).

The runtime is just the files:

- `lib/prelude.h`
- `lib/prelude.c`

Again @jacereda you're the only other person who's [committed](https://github.com/austral/austral/commit/3e31f3eeed42fc80c325d93986a7863364728b9d) to the runtime: do you approve of making this change?

**Comment by jacereda** [comment]
Again, no problem.

**Comment by eudoxia0** [comment]
Superseded by #421
