### ISSUE TITLE
Licensing the built-in modules as Apache 2.0

### ISSUE THREAD

**Issue by eudoxia0** [austral/austral#410]
As in #390 and #409 

The built-in modules are compiled every time alongside user code, so they should be permissively licensed. I should have done this from the start but since it was a personal project for a long time I never thought to do this.

The builtins are the files:

- `lib/builtin/Memory.aui`
- `lib/builtin/Memory.aum`
- `lib/builtin/Pervasive.aui`
- `lib/builtin/Pervasive.aum`

@jacereda and @qbradley you two are the only other people who have contributed to the builtins. Do you approve of this change?

**Comment by jacereda** [comment]
No problem on my side.

**Comment by eudoxia0** [comment]
Superseded by #421
