### ISSUE TITLE
Dereference operator is ambiguous

### ISSUE THREAD

**Issue by eudoxia0** [austral/austral#414]
From Discord via @ckp95:

```
(!foo)->bar
!(foo->bar)
```

**Comment by ckp95** [comment]
Context from the Discord:

>eudoxia: Right now the default behaviour of path expressions starting from references is they push the reference in, so if you do `ref->x->y->z` you get a reference to `z`, while dereferencing is explicit. Maybe it should be the other way around, since dereferencing is more common, and you'd have some other expression to get inner references, something like `foo(ref->x->y->z)`

Simplest change would be to require full parentheses: `!foo->x` would be a syntax error, you would have to do `(!foo)->x` or `!(foo->x)`.

By the way, are we allowed to stack `!` to dereference many times? Like `!!!foo` to chase pointers three layers deep ...

**Comment by ishehadeh** [comment]
Just ran into this and went looking for an issue. 


> goofy idea: put dereferencing as a component of the path itself, rather than as its own thing. 
> [...]
> ie a giant postfix operator, evaluated left to right

I really like this idea, actually.  It makes it clear at a glance exactly what is being dereferenced, IMO.

The only thing is it seems like it would sneak in a new way to do pointer slot access.
For example, I *think* these two would be equivalent:

```austral 
a->b->c

a->b!.c
```

**Comment by eudoxia0** [comment]
Can you explain how you ran into the ambiguity? Did you write some code that parsed wrong? Thanks!

**Comment by eudoxia0** [comment]
Zig has an interesting syntax: `*foo` becomes `foo.*`, and `*(a.b.c)` becomes `a.b.c.*`.

**Comment by eudoxia0** [comment]
I might change the deref syntax in the future, but I'm closing this for now because it's not actually ambiguous: because of how the type-checker works, field access syntax in Austral is not associative, that is, `a.b.c` is not `(a.b).c`, they cannot be typechecked separately (because if `b` has a Linear type, `(a.b).c` would fail, but `a.b.c` would pass, because paths must end in a Free type).

So, `a.b.c` is always an atomic expression, and so `!a.b.c` is not actually ambiguous.
