### ISSUE TITLE
:=/= typo causes unexpected type conversion

### ISSUE THREAD

**Issue by ckp95** [austral/austral#423]
Found this while attempting to do something else:

```
module body MutateVar is
    generic [R: Region]
    function mutate_int(var: &![Int32, R]): Unit is
        !var = 10; -- typo
        return nil;
    end;

    function main(): ExitCode is
        let x: Int32 := 5;
        printLn(x);

        mutate_int(&!x);
        printLn(x);

        return ExitSuccess();
    end;
end module body.
```

This unexpectedly compiles. The line `!var = 10;` has a typo, I meant to write `:=`.

The `=` is equality comparison, and the spec says both sides must be `Bool`. For this to compile, the integers on both sides must have been implicitly converted to `Bool`, which goes against the "no implicit type conversions anywhere" item on the antifeature list. So this seems like a bug.

---

EDIT wait no, what am I saying. The code should(?) compile. The bug is in the spec:

![image](https://user-images.githubusercontent.com/43073868/217672140-8b037399-56d6-4ca4-9c8a-01898063856d.png)

highlighted part, a and b can't just be boolean expressions.

**Comment by eudoxia0** [comment]
Oh yeah the spec is wrong here.

**Comment by eudoxia0** [comment]
Spec fixed here: https://github.com/austral/austral.github.io/pull/58

**Comment by eudoxia0** [comment]
In the future, I should probably add a warning about non-function calls in a discarding expression, since those are clearly in error.
