### ISSUE TITLE
Numeric conversion has an inconvenient API

### ISSUE THREAD

**Issue by eudoxia0** [austral/austral#429]
The numeric conversion APIs return `Option` types. This is tiresome to unwrap. There should be a version of the API that aborts on failure, e.g. to make the code simpler for numeric literals.

Two ways to go about this:

1. `toT` function is abortive, `toTMaybe` function returns `Option` (breaks existing API, which is fine really)
2. `toT` function returns `Option` (as in now), `toTUnsafe` function does the abort.

**Comment by kenaryn** [comment]
Like in V, there could be a Result type, which is a Union having `error | `value` as inhabitants.

**Comment by eudoxia0** [comment]
Not worth cluttering up the issues page yet. Arguably the right solution is to have multiple typeclasses like Rust (`Into` and `TryInto`).
