### ISSUE TITLE
Proposal: Modulo Operation in Austral.Pervasive

### ISSUE THREAD

**Issue by Atli-A** [austral/austral#447]
# Proposal
The following is a proposal for the interface for modulo in austral
```
typeclass NatModuloOp(T: Type) is
  -- Only implemented for only unsigned integer types as to be entirely unambiguous 
  -- remainder function with no footguns
  method umod(lhs: T, rhs: T): T;
end;

typeclass IntModuloOp(T: Type) is
  -- Implemented only for signed types. 
  -- Not named mod in order to force the programmer to choose between umod and smod
  -- Implemented as python-style modulo 
  method smod(lhs: T, rhs: T): T;
end;

typeclass FloatModuloOp(T: Type) is
  -- Explicit floating point only mod operator performs exactly as specified by IEEE 754.
  method fmod(lhs: T, rhs: T): T;
end;
```

## Strengths
- Floating point modulo are separated and cannot be confused with other modulo implementations
- `umod` removes footguns involving a negative lhs and/or a negative rhs
- `smod` makes the programmer think about the implications about using signed modulo and its behavior

## Flaws
- Aborts on modulo by zero
- `smod` implementation was chosen somewhat arbitrarily by me 

# Alternatives
## Division By Zero
One solution is to require NonZero for the denominator
```
record NonZero[T: Free]: Free is
  value: T;
end;

typeclass MakeNonZero(T: Free) is
  -- aborts on failure
  method makeNonZeroOrFail(n: T): NonZero[T]; 
  method makeNonZeroSafe(n: T): Option[NonZero[T]];
end;
```
Using this would make the type signatures of  `umod` and `smod`  be
`method smod(lhs: T, rhs: NonZero[T]): T;`
`method umod(lhs: T, rhs: NonZero[T]): T;`
This 

## Signed Modulo implementation
I am admittedly inexperienced in this area. 
The only signed integer modulo handling I am familiar with come from Python and C.
### Why I didn't choose the C-style
As far as I understand C's modulo for negative numbers is equivalent to
```
int smod(int lhs, int rhs) {
  int lhs_sign = (lhs < 0) ? -1 : 1;
  return umod(abs(lhs), abs(rhs));
}
```
This being so simple to implement yet so rarely used suggests that this is a footgun used unintentionally.
### Why I chose the Python-style
[This](https://stackoverflow.com/a/3883019) convincing argument.

## Default to hardware
We could just default to the architecture's modulo.
I think this is a bad idea as it will create inconsistencies. Additionally, some architectures may not implement it which forces us to decide how it works anyway.

## No signed `rhs` for `smod`
There are some arguments that a negative number on the rhs is not useful enough to be allowed as it will be used unintentionally.
Austral only allows for typeclasses to have one generic type (for now).
This means that `smod` would likely need to be implemented as:
```
method smod(lhs: T, rhs: Nat64): T
```

# Resources from other langs
[Golang dev justifies it's modulo](https://github.com/golang/go/issues/448#issuecomment-66049769)
[Guido van Rossum mentions it when talking about flooring division](http://python-history.blogspot.com/2010/08/why-pythons-integer-division-floors.html)

Feedback is welcome :)

**Comment by eudoxia0** [comment]
I will probably have to study this in a bit more detail, I have probably used modulo like six times in my entire career.

**Comment by GamesByDavidE** [comment]
P.S. you could change the spellings of `t_div` and `t_mod`. (Or any of the other spellings. Not here to bike-shed.) I know Haskell uses `quot` and `rem` respectively.

We could add `t_div_mod` for regularity.

I didn't discuss error handling much because I'm sure that @eudoxia0 will have an opinion. Personally I've always been happy to write my own wrappers as needed.

**Comment by GamesByDavidE** [comment]
Copying one more comment from the Discord: `method smod(lhs: T, rhs: Nat64): T` is a foot-gun with floor division semantics since `smod(-1, big number)` is liable to overflow.

**Comment by eudoxia0** [comment]
After Ada, I think it makes sense to implement `rem` as truncated remainder. Ada's `rem` is C's `%`.
