### ISSUE TITLE
Overflowing integers at compile time shouldn't be possible

### ISSUE THREAD

**Issue by Atli-A** [austral/austral#458]
Overflowing integers at compile time shouldn't be possible. Example:
File  `main.aum`
```
module body Main is
    function main(): ExitCode is
        let a: Int32 := 100000000000000000000;
        printLn(a);
        return ExitSuccess();
    end;
end module body.
```
running with `austral compile main.aum --entrypoint=Main:main --output=test && ./test`
output:
```
1661992960
```

expected output:
```
Type Error: Provided Integer too large for type `Int32`
etc etc
```
In my opinion this should not compile when the integer is too large to prevent bugs.

This seems easy to fix at first but then we run into situations like
```
let a: Int32 := (5 * 20) * 100000000;
```
should the compiler handle solve mathematical operations at compile time when all variables and/or constants are known? that adds complexity.

Possibly related to #432 and #433

**Comment by eudoxia0** [comment]
You're right, this is something I consciously left as a TODO but should be fixed.
