### ISSUE TITLE
Standard.Buffer:initialize fails with size=0

### ISSUE THREAD

**Issue by eudoxia0** [austral/austral#469]
Reported by MilkManDan on Discord:

>I was messing around with some of the tests in the stdlib, specifically Buffer. For the initialize function, what is the expected behavior if 0 is passed as the size? I assumed it would be equivalent to allocateEmpty but it throws an error saying Overflow in trappingSubtract (Index). Here is the test I added to the Buffer tests

Expected behaviour: should behave like `allocateEmpty`.

**Comment by d-gaston** [comment]
Hi, I'm the one who reported the bug, I'd like to try to work on this, if possible

**Comment by eudoxia0** [comment]
> Hi, I'm the one who reported the bug, I'd like to try to work on this, if possible

Great! The relevant code is:

https://github.com/austral/austral/blob/8a131138c89d3ec3de48a88707cd97da6df33711/standard/src/Buffer.aum#L98-L125

To build the compiler and then build and test the standard library:

```
git clone https://github.com/austral/austral.git
cd austral/
make
sudo make install
cd standard/
make
./test_bin
```
