### ISSUE TITLE
Unknown version requirements for dependencies

### ISSUE THREAD

**Issue by Costava** [austral/austral#505]
Neither the `dune-project` nor the `install-ocaml-deps.sh` state which versions/ranges of the dependencies are needed (other than for `ppxlib`).

If ranges are not known, it would be good to at least know which versions `austral` is tested/developed/known to work with.

**Comment by eudoxia0** [comment]
Yeah I don't know how to build an opam file. In practice the versions are what's pinned in `shell.nix`.
