### ISSUE TITLE
How to get "argc" and "argv"?

### ISSUE THREAD

**Issue by Costava** [austral/austral#530]
How can an austral program get the arguments passed to it on a command line?

I imagine it would be through the RootCapability of the main function, but I don't see anywhere how this is done.

**Comment by eudoxia0** [comment]
In the `Austral.Pervasive` module (which is automatically imported) there are functions:

```
function argumentCount(): Index;

function nthArgument(n: Index): FixedArray[Nat8];
```

This should and eventually will go through the capability system.

**Comment by eudoxia0** [comment]
For an example of using this, see: https://raw.githubusercontent.com/austral/austral/7258a54322cbcd8a0ebe32450657be6d435ab748/test-programs/suites/001-trivial/010-cli/Test.aum
