### ISSUE TITLE
Char literal of '\n' is 97 instead of 10.

### ISSUE THREAD

**Issue by Blugatroff** [austral/austral#577]
This program should print 10, but it prints 97 instead. For every other character i tried the correct ASCII value was returned.
```
module body Example.Foo is
    function main(): ExitCode is
        printLn('\n');
        return ExitSuccess();
    end;
end module body.
```

I noticed this when using `Standard.IO.Terminal (readLine)` because it would only read up to the first 'a' ('a' is 97 in ASCII).
I wondered whether this could be intentional and maybe character literals in austral aren't supposed to be ASCII, but since '\r' for example correctly equals 13 i don't think that's the case.

**Comment by AlbertoGP** [comment]
This looks like a typo to me, in the function `parse_ascii_char(string)` in Util.ml: https://github.com/austral/austral/blob/master/lib/Util.ml#L116
I have prepared a trivial PR that fixes it: #580
