### ISSUE TITLE
borrow checker ?

### ISSUE THREAD

**Issue by MohamedGhardallou** [austral/austral#586]
Hello,
Is it possible to borrow a linear variable as a read only reference and a mutable reference at the same time ?
I cannot find this mention any where in the documentation.

Thanks

**Comment by eudoxia0** [comment]
>  Is it possible to borrow a linear variable as a read only reference and a mutable reference at the same time ?

No, this leads to unsound behaviour.

Imagine you have a Box type (like in Rust) that contains a pointer to some heap-allocated value. You have a read-reference and a write-reference to the box.

Then you turn the read-reference into a reference to the heap-allocated value (by following the pointer, basically).

Then you use the write-reference to deallocate that value.

Now the read-reference is dangling.

So borrowing is "(any number of immutable borrows) XOR (exactly one mutable borrow)".
