### ISSUE TITLE
FFI functions returning void or pointers to unknown types

### ISSUE THREAD

**Issue by xz47sv** [austral/austral#588]
As far as I can tell there is no way to return nothing or return pointer to something other than some of the basic types from Foreign_Import, would it be possible to introduce a type for void pointers or a way to bind a record to some opaque type that can only be constructed by a function behind the ffi boundary?

One way of doing this that I thought of would be to have a Void type which could be restrained to be only used in unsafe modules and then we could do this:

```
pragma Unsafe_Module;

import Austral.Memory(Pointer);

module body FFI is
    record File: Linear is
        inner: Pointer[Void];
    end;

    pragma Foreign_Import(External_Name => "fopen");
    function fopen(
        pathname: Span[Nat8, Static], mode: Span[Nat8, Static]
    ): Pointer[Void] is end;

    pragma Foreign_Import(External_Name => "fclose");
    function fclose(ptr: Pointer[Void]): Int32 is end;

    function openFile(
        pathname: Span[Nat8, Static], mode: Span[Nat8, Static]
    ): File is
        -- should have a nullCheck, but this is just to convey a point
        return File(inner => fopen(pathname, mode));
    end;

    function closeFile(file: File): Unit is
        { inner: Pointer[Void] } := file;
        fclose(inner);
    end;
end module body.
```

likewise with just plain Void type not surrounded by Pointer[] we could interface with functions that have no return value, hitting two birds with one stone. Maybe the type could also be part of the Memory module next to the other unsafe stuff.

If there is a reason you don't want this or if there is some other way you'd like to do things could you tell me? I'd be willing to implement this if it's something you are onboard with and could give me a few pointers on how to do things.

**Comment by eudoxia0** [comment]
> a type for void pointers

The main reason for this is to not complicate the type system with a special-use type that can only be used as a type argument to `Pointer[]`. When I need a generic `void*` type for the FFI I just use `Pointer[Nat8]`.

**Comment by xz47sv** [comment]
I didn't think C was that benevolent and just let's you use uint8_t in place of void pointers and compiles, but I guess it is :D
